### ISSUE TITLE
Peer to peer module 1 week 2

### ISSUE THREAD

**Issue by enmanuelbayen** [romans-adi/AwesomeBooksES6#2]
Great work with the functionality of your main and additional functions!

I kindly suggest in this [file](https://github.com/romans-adi/AwesomeBooksES6/blob/382072e9efe91652c53d301e2465bda353ef41d5/js/modules/sectionsToggle.js#L17) remove the export of each function and put at the end <export {func1, func2, func3};> as it will make your code more visually clean. 

- when removing all the books from the list it left an empty square. Kindly improve that functionallity.

 - EmptyListWarning was imported in main JS file but it wasn't necessary to create an specific file for it. Please, consider migrate the code of that file to then safetly remove it so that your project will look better organized.

**Comment by romans-adi** [comment]
Thank you so much for your suggestions! 

I used the correct export for sections toggle and completely removed the emptyListWarning module adding this logic in the Book class method displayAllBooks instead.
